### ISSUE TITLE
Unable to compile on Crystal 0.31.0

### ISSUE THREAD

**Issue by Hentioe** [icyleaf/markd#21]
Changing `/` to `//` can solve some errors, and adding a return type to the overridden method can eliminate some warnings.

However, Channel was refactored and the [Channel::Buffered(T)#full?](https://crystal-lang.org/api/0.30.1/Channel/Buffered.html#full?-instance-method) method was removed. I don't know how to modify it, so I didn't open a PR.

**Comment by icyleaf** [comment]
@Hentioe i fix it but i did not found what you figure issue, would you explain it please?

**Comment by Hentioe** [comment]
Has been fixed.
