### ISSUE TITLE
Error: no overload matches 'String#*' with type (Float64 | Int32)

### ISSUE THREAD

**Issue by drujensen** [icyleaf/markd#23]
getting a compilation error using `Markd.to_html(markdown)`
```
In lib/markd/src/markd/parsers/inline.cr:460:26

 460 | "\u{2014}" * em_count + "\u{2013}" * en_count
                  ^
Error: no overload matches 'String#*' with type (Float64 | Int32)

Overloads are:
 - String#*(times : Int)
Couldn't find overloads for these types:
 - String#*(times : Float64)

```

shards.yml
```
  markd:
    github: icyleaf/markd
    version: 0.1.2
```

If I change to `"\u{2014}" * em_count.to_i + "\u{2013}" * en_count.to_i` then it compiles and seems to work.

**Comment by elorest** [comment]
I fixed this on my branch and then noticed it's already been fixed on master.

In Crystal 0.31 `3/2 => 1.5`

I don't see that in the breaking change list...

Apparently 3//2 => 1 though.

**Comment by elorest** [comment]
@icyleaf Is master stable enough to be released as 0.2.0?

**Comment by elorest** [comment]
https://github.com/crystal-lang/crystal/pull/8120

**Comment by icyleaf** [comment]
I'm on vacation now, you can use `master` branch.

**Comment by icyleaf** [comment]
Close for no response, feel free to file new issue or reopen.

**Comment by drujensen** [comment]
@icyleaf Thanks for releasing a fix.
