### ISSUE TITLE
Support Front Matter?

### ISSUE THREAD

**Issue by takanotume24** [icyleaf/markd#31]
Hello, thank you for a very easy to use library!
I'd like to ask, do you plan to support https://jekyllrb.com/docs/front-matter/ ?
This is a format supported by Grav, a flat file CMS, or Github. (But it's not a standard form, I guess ...)
I looked at the source code to try to make it work, but my programming skills didn't allow me to figure it out. 
If you can deal with it, I would appreciate it.
Thank you．

**Comment by takanotume24** [comment]
It's a simple one, but I made a wrapper library to try it out. 
https://github.com/takanotume24/front-matter-markd
The implementation is to match the pattern(``---``) with a regular expression and let the yaml parser process it.

**Comment by icyleaf** [comment]
Compliant to CommonMark specification (v0.27).
