### ISSUE TITLE
Reason why Markd::Options is a struct ?

### ISSUE THREAD

**Issue by Nephos** [icyleaf/markd#39]
Hello,

I'm working on a home-made patch, [using Markd as a code base](https://git.sceptique.eu/Sceptique/wikicr/src/branch/master/src/lib/wikimd/markd_patch.cr).

I'm making my own classes inheriting from Markd to be able to get most of the next update without too much effort (If you have a better idea I'd like to know :D) so I can add my custom behavior over the default markdown.
I want it mostly to add internal links, tagging, and minor CSS features I will add in the futur.

But I have this thing with Options wich is a structure... so `A struct cannot inherit from a non-abstract struct`. Which means I must fork manually to change it to a class. Any reason you put it this way ? Want to change maybe ? ;) ;)

Evening !

**Comment by icyleaf** [comment]
It was changed to `Class` (#36) but not release yet, use `master` branch to apply it for emergency

**Comment by icyleaf** [comment]
UPDATE: `shards update` to upgrade markd version to `0.4.1`

**Comment by Nephos** [comment]
<3 Great thanks!
