### ISSUE TITLE
Lesser-than sign in code block isn't escaped

### ISSUE THREAD

**Issue by vulpivia** [icyleaf/markd#48]
This is a bug I detected while using the Crystal documentation generator, but since that uses markd, I'm assuming a bug report here makes more sense.

Creating documentation for the following code

```crystal
# `<test`
module Test
end
```

inserts `<code><test</code>` into the final documentation. Expected behavior would be transforming `<` into `&lt;` inside code tags.

**Comment by straight-shoota** [comment]
This is actually a bug in the Crystal compiler's usage of this shard: https://github.com/crystal-lang/crystal/issues/11685 It has been fixed since 1.3.1.

`markd` itself is not affected, it should properly escape inline code.

**Comment by vulpivia** [comment]
Oh, must have missed that issue. Thank you, this can be closed then.
