### ISSUE TITLE
May I maintain this repository?

### ISSUE THREAD

**Issue by HOMODELUNA** [icyleaf/markd#52]
Hello, I'm just a freshman crystal programmer. On seeing your banner searching for maintainers, I would like to recommend myself for the position. Though I'm not much skilled, I have spare time, interest for this repository. Also I'm working on translating crystal language references into [Chinese Version](https://github.com/HOMODELUNA/crystal-book-zh_CN)

In fact, I'm depending on this lib for my pirate gitbook project [gitbook.cr](https://github.com/HOMODELUNA/gitbook.cr), so I forked this repo, trying to add traverse and inspect functionality for nodes.

**Comment by icyleaf** [comment]
Thank you very much for your interest in this project. I haven't seen your contribution to the Crystal community yet (not just the Chinese translation), I suggest you make some changes after fork markd, and submit PRs to the Crystal organization then we will re-update.
