### ISSUE TITLE
 invalid identity escape in regular expression' in Firefox 

### ISSUE THREAD

**Issue by klaybloom** [icyleaf/markd#66]

**Comment by nobodywasishere** [comment]
Do you have more information about the issue you're running into?

**Comment by klaybloom** [comment]
It will prompt that there is a problem with the regular expression, resulting in the inability to display the markdown format.

**Comment by nobodywasishere** [comment]
Can you give me the exact error it gives and an example of what markdown you're running that gives the error?

**Comment by icyleaf** [comment]
Such like:

- raw markdown content
- expect output
- got output (exception trace etc)
